name: soul-plane
services:
  mysqldb:
    image: mysql
    restart: always
    environment: 
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - '3006:3006'
    volumes:
      - db:/var/lib/mysql
      - ./src/database/ddl.sql:/docker-entrypoint-initdb.d/init.sql
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 55767:55767
volumes:
  db:
    driver: local
